{"name": "测试数据：【 tech020@hzdusun.com，Djl123456，True，1000，登录成功】", "status": "failed", "statusDetails": {"message": "AssertionError: 接口返回码是 【 10000 】, 返回信息：Ok! \nassert False == True", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x0000015E8CF55100>\nusername = 'tech020@hzdusun.com', password = 'Djl123456', except_result = True\nexcept_code = 1000, except_msg = '登录成功'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    # @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    # @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n>       assert result.success == except_result, result.error\nE       AssertionError: 接口返回码是 【 10000 】, 返回信息：Ok! \nE       assert False == True\n\ntest_03_login.py:30: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'tech020@hzdusun.com'"}], "start": 1701768991578, "stop": 1701768991578}], "attachments": [{"name": "log", "source": "e34a4af4-e9cd-4b5e-b432-bf965d7dfe46-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "1a8b7a37-9104-4dc9-90fe-c6829793f3bb-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "baa52c67-f5aa-4fd7-9210-ab4d3068e83c-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'tech020@hzdusun.com'"}, {"name": "password", "value": "'Djl123456'"}, {"name": "except_result", "value": "True"}, {"name": "except_code", "value": "1000"}, {"name": "except_msg", "value": "'登录成功'"}], "start": 1701768990998, "stop": 1701768991578, "uuid": "36bbef62-0a9e-4d03-8b00-b57a5bcab3aa", "historyId": "f14bdf7a8cff39d40a446eccfc1deb68", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户登录模块"}, {"name": "epic", "value": "针对单个接口的测试"}, {"name": "story", "value": "用例--登录用户"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-LLVNPLO"}, {"name": "thread", "value": "27316-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}]}