{"name": "测试数据：【 测试test，123456，False，10001，111】", "status": "failed", "statusDetails": {"message": "AssertionError: assert '111' in 'Email address not exist!'\n +  where 'Email address not exist!' = <core.result_base.ResultBase object at 0x0000028049459520>.msg", "trace": "self = <testcases.api_test.test_03_login.TestUserLogin object at 0x00000280494634C0>\nusername = '测试test', password = '123456', except_result = False\nexcept_code = 10001, except_msg = '111'\n\n    @allure.story(\"用例--登录用户\")\n    @allure.description(\"该用例是针对获取用户登录接口的测试\")\n    # @allure.issue(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应BUG的链接地址\")\n    # @allure.testcase(\"https://www.cnblogs.com/wintest\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"测试数据：【 {username}，{password}，{except_result}，{except_code}，{except_msg}】\")\n    @pytest.mark.single\n    @pytest.mark.parametrize(\"username, password, except_result, except_code, except_msg\",\n                             api_data[\"test_login_user\"])\n    def test_login_user(self, username, password, except_result, except_code, except_msg):\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = login_user(username, password)\n        step_1(username)\n        assert result.success == except_result, result.error\n        assert result.response.status_code == 200\n        assert result.success == except_result, result.error\n        logger.info(\"code ==>> 期望结果：{}， 实际结果：【 {} 】\".format(except_code, result.response.json().get(\"code\")))\n        assert result.response.json().get(\"code\") == except_code\n>       assert except_msg in result.msg\nE       AssertionError: assert '111' in 'Email address not exist!'\nE        +  where 'Email address not exist!' = <core.result_base.ResultBase object at 0x0000028049459520>.msg\n\ntest_03_login.py:35: AssertionError"}, "description": "该用例是针对获取用户登录接口的测试", "steps": [{"name": "步骤1 ==>> 登录用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}], "start": 1701826895414, "stop": 1701826895414}], "attachments": [{"name": "log", "source": "8a8d3a7f-9c7f-4c64-ba11-90b452751115-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "d4664d63-4c83-4153-9a71-03086d84ceb2-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "password", "value": "'123456'"}, {"name": "except_result", "value": "False"}, {"name": "except_code", "value": "10001"}, {"name": "except_msg", "value": "'111'"}], "start": 1701826894972, "stop": 1701826895415, "uuid": "69e70e83-b7ca-42fd-a788-a923bd05c0e5", "historyId": "de94bf95e37024d1350e9440c3fbfa4d", "testCaseId": "7272db244dabef390096479ae3196642", "fullName": "testcases.api_test.test_03_login.TestUserLogin#test_login_user", "labels": [{"name": "epic", "value": "针对单个接口的测试"}, {"name": "story", "value": "用例--登录用户"}, {"name": "severity", "value": "normal"}, {"name": "feature", "value": "用户登录模块"}, {"name": "tag", "value": "single"}, {"name": "parentSuite", "value": "testcases.api_test"}, {"name": "suite", "value": "test_03_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-LLVNPLO"}, {"name": "thread", "value": "27336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.api_test.test_03_login"}]}